spring:
  #nacos配置
  cloud:
    nacos:
      # 服务注册
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: e1f396fa-152f-4415-8733-8c853ae9ac1f
      # 配置中心
      config:
        server-addr: ${spring.cloud.nacos.discovery.server-addr}
        namespace: e1f396fa-152f-4415-8733-8c853ae9ac1f
        file-extension: yml

# rocketmq 配置
rocketmq:
  name-service: 127.0.0.1:9876
  producer-group: demo-producer-group
  consumer-group: demo-consumer-group
  retry-times: 0
  topic: FFSONG_DEMO